name: Docs
on: 
  push:
    branches:
      - develop
    # TODO: Keep all historical builds (like the js-sdk)
    #tags: ['v*']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build and deploy docs
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        BRANCH: gh-pages
        BUILD_SCRIPT: "yarn install && yarn docs"
        FOLDER: ".jsdoc/matrix-bot-sdk/${{ steps.extract_branch.outputs.branch }}"
