FROM node:14-alpine AS builder

WORKDIR /opt/mx-puppet-slack

RUN apk --no-cache add git python2 make g++ pkgconfig \
    build-base \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    musl-dev \
    giflib-dev \
    pixman-dev \
    pangomm-dev \
    libjpeg-turbo-dev \
    freetype-dev

# run build process as user in case of npm pre hooks
# pre hooks are not executed while running as root
RUN chown -R node:node /opt/mx-puppet-slack
USER node

COPY --chown=node:node package.json yarn.lock ./
COPY --chown=node:node packages/ ./packages
RUN yarn && cd packages/mx-puppet-slack && yarn build

FROM node:14-alpine

ARG TARGETARCH=amd64

VOLUME /data

ENV CONFIG_PATH=/data/config.yaml \
    REGISTRATION_PATH=/data/slack-registration.yaml

RUN apk add --no-cache bash curl jq && \
  curl -sLo yq https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_${TARGETARCH} && \
  chmod +x yq && mv yq /usr/bin/yq
RUN apk add --no-cache su-exec \
    cairo \
    jpeg \
    pango \
    musl \
    giflib \
    pixman \
    pangomm \
    libjpeg-turbo \
    freetype

WORKDIR /opt/mx-puppet-slack
COPY packages/mx-puppet-slack/docker-run.sh ./
COPY --from=builder /opt/mx-puppet-slack ./

# change workdir to /data so relative paths in the config.yaml
# point to the persistent volume
WORKDIR /data
ENTRYPOINT ["/opt/mx-puppet-slack/docker-run.sh"]
