bridge:
  # Address for the bridge to bind to; if running as a Docker container, you
  # probably want 0.0.0.0 here
  bindAddress: localhost
  # Port to host the bridge on which your homeserver will connect to
  port: 6000
  # Name of your homeserver
  domain: matrix.myhomeserver.com
  # URL where the bridge can connect to your homeserver
  homeserverUrl: http://localhost:8008
  # Optionally specify a different media URL used for the media store
  #mediaUrl: https://external-url.org
  # This enabled automatic double-puppeting:
  # A map for shared secrets of the homeserver URL to the shared secret
  # See https://github.com/devture/matrix-synapse-shared-secret-auth
  #loginSharedSecretMap:
  #  yourserver.com: supersecretsharedsecret
  # optionally override the display name of the bridge bot
  #displayname: Protocol Bot
  # optionally set the avatar of the bridge bot
  #avatarUrl: mxc://yourserver.com/somefile
  # optionally enable group synchronisation.
  # Needs synapse config "enable_group_creation" set to true
  #enableGroupSync: true
  # Strip the homeserver url from pings that are on these homeservers in the body
  #stripHomeservers:
  # - example.org

logging:
  # Log level of console output
  # Allowed values starting with most verbose:
  # silly, debug, verbose, info, warn, error
  console: info
  # Optionally, you can apply filters to the console logging
  #console:
  #  level: info
  #  enabled:
  #    - Store
  #  disabled:
  #    - PresenceHandler

  # Date and time formatting
  lineDateFormat: MMM-D HH:mm:ss.SSS
  # Logging files
  # Log files are rotated daily by default
  files:
    # Log file path
    - file: "bridge.log"
      # Log level for this file
      # Allowed values starting with most verbose:
      # silly, debug, verbose, info, warn, error
      level: info
      # Date and time formatting
      datePattern: YYYY-MM-DD
      # Maximum number of logs to keep.
      # This can be a number of files or number of days.
      # If using days, add 'd' as a suffix
      maxFiles: 14d
      # Maximum size of the file after which it will rotate. This can be a
      # number of bytes, or units of kb, mb, and gb. If using the units, add
      # 'k', 'm', or 'g' as the suffix
      maxSize: 50m
      # Optionally enable/disable logging for certain modules
      #disabled:
      #  - PresenceHandler
      #  - module: bot-sdk-MatrixLiteClient
      #    regex: /_matrix/client/r0/presence/ # this regex needs to match to disable the log
      #enabled:
      #  - Store

database:
  # Use Postgres as a database backend
  # If set, will be used instead of SQLite3
  # Connection string to connect to the Postgres instance
  # with username "user", password "pass", host "localhost" and database name "dbname".
  # Modify each value as necessary
  #connString: "postgres://user:pass@localhost/dbname?sslmode=disable"
  # Use SQLite3 as a database backend
  # The name of the database file
  filename: database.db

provisioning:
  # Regex of Matrix IDs allowed to use the puppet bridge
  whitelist:
    # Allow a specific user
    #- "@user:server\\.com"
    # Allow users on a specific homeserver
    - "@.*:yourserver\\.com"
    # Allow anyone
    #- ".*"
  # Regex of Matrix IDs forbidden from using the puppet bridge
  #blacklist:
    # Disallow a specific user
    #- "@user:server\\.com"
    # Disallow users on a specific homeserver
    #- "@.*:yourserver\\.com"

presence:
  # Bridge online/offline status
  enabled: true
  # How often to send status to the homeserver in milliseconds
  interval: 500
  # if the im.vector.user_status state setting should be enabled
  #enableStatusState: false
  # A blacklist of remote user IDs for the im.vector.user_status state setting
  #statusStateBlacklist:
  # - baduser

relay:
  # Regex of Matrix IDs to allow to use the relay mode
  # Same format as in provisioning
  whitelist:
    - "@.*:yourserver\\.com"
  #blacklist:
    #- "@user:yourserver\\.com"

selfService:
  # Regex of Matrix IDs who are allowed to use bridge self-servicing (plumbed rooms)
  # Same format as in provisioning
  whitelist:
    - "@.*:yourserver\\.com"
  #blacklist:
    #- "@user:yourserver\\.com"

# Map certain homeserver URLs to the C-S API endpoint
# Useful for double-puppeting if .well-known is unavailable for some reason
#homeserverUrlMap:
#  yourserver.com: http://localhost:1234

namePatterns:
  # Override the protocols set default name patterns
  # Which variables are available depends on protocol implementation
  user: :name
  userOverride: :name
  room: :name
  group: :name

# Prometheus metrics configuration
metrics:
  # If enabled, the metrics are served at http://localhost:$port$path
  enabled: false
  # On which port the prometheus metrics will be served
  port: 8000
  # Path on which the metrics are available, the default is /metrics
  path: "/metrics"

limits:
  # Up to how many users should be auto-joined on room creation? -1 to disable
  # Defaults to 200
  #maxAutojoinUsers: 200
  # How long the delay between two autojoin users should be, in millisectonds.
  # Defaults to 5000
  #roomUserAutojoinDelay: 5000
