language: node_js
env:
- NODE_ENV=development
before_install:
- npm i -g yarn
install:
- yarn install
jobs:
  include:
  - name: Build Node 10
    script: yarn build
    node_js: 10
  - name: Linter
    script: yarn lint
    node_js: 10
  - name: Tests
    script: yarn test
    node_js: 10
